name: Test and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload site
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download site
        uses: actions/download-artifact@v3
        with:
          name: site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: .
